# kvraft YCSB workload B: 95% reads, 5% updates.
workload=site.ycsb.workloads.CoreWorkload
recordcount=1000
operationcount=1000
fieldcount=1
fieldlength=256
readallfields=true
writeallfields=true
readproportion=0.95
updateproportion=0.05
scanproportion=0
insertproportion=0
requestdistribution=zipfian
