# kvraft YCSB workload C: 100% reads.
workload=site.ycsb.workloads.CoreWorkload
recordcount=1000
operationcount=1000
fieldcount=1
fieldlength=256
readallfields=true
writeallfields=true
readproportion=1
updateproportion=0
scanproportion=0
insertproportion=0
requestdistribution=zipfian
